#!/usr/bin/env python3
# Generated by usbrply
# cmd: /home/benoit/anaconda3/bin/usbrply --wrapper --device 5 -p fli_init.pcapng

import binascii
import time
import usb1


def validate_read(expected, actual, msg):
    if expected != actual:
        print('Failed %s' % msg)
        print('  Expected; %s' % binascii.hexlify(expected,))
        print('  Actual:   %s' % binascii.hexlify(actual,))
        #raise Exception("failed validate: %s" % msg)


def replay(dev):
    def bulkRead(endpoint, length, timeout=None):
        return dev.bulkRead(endpoint, length, timeout=(1000 if timeout is None else timeout))

    def bulkWrite(endpoint, data, timeout=None):
        dev.bulkWrite(endpoint, data, timeout=(1000 if timeout is None else timeout))
    
    def controlRead(bRequestType, bRequest, wValue, wIndex, wLength,
                    timeout=None):
        return dev.controlRead(bRequestType, bRequest, wValue, wIndex, wLength,
                    timeout=(1000 if timeout is None else timeout))

    def controlWrite(bRequestType, bRequest, wValue, wIndex, data,
                     timeout=None):
        dev.controlWrite(bRequestType, bRequest, wValue, wIndex, data,
                     timeout=(1000 if timeout is None else timeout))

    def interruptRead(endpoint, size, timeout=None):
        return dev.interruptRead(endpoint, size,
                    timeout=(1000 if timeout is None else timeout))

    def interruptWrite(endpoint, data, timeout=None):
        dev.interruptWrite(endpoint, data, timeout=(1000 if timeout is None else timeout))

    # Generated by usbrply
    # Source: Linux pcap (usbmon)
    # cmd: /home/benoit/anaconda3/bin/usbrply --wrapper --device 5 -p fli_init.pcapng
    # Generated from packet 73/74
    controlWrite(0x40, 0xA0, 0x7F92, 0x0000, b"\x01")
    # Generated from packet 75/76
    controlWrite(0x40, 0xA0, 0xE600, 0x0000, b"\x01")
    # Generated from packet 77/78
    controlWrite(0x40, 0xA0, 0x7F92, 0x0000, b"\x01")
    # Generated from packet 79/80
    controlWrite(0x40, 0xA0, 0xE600, 0x0000, b"\x01")
    # Generated from packet 81/82
    controlWrite(0x40, 0xA0, 0x0000, 0x0000, b"\x02\x02\x3A\x02\x01\xBC")
    # Generated from packet 83/84
    controlWrite(0x40, 0xA0, 0x000B, 0x0000, b"\x02\x05\x84")
    # Generated from packet 85/86
    controlWrite(0x40, 0xA0, 0x0013, 0x0000, b"\x02\x01\xBC")
    # Generated from packet 87/88
    controlWrite(0x40, 0xA0, 0x001B, 0x0000, b"\x02\x01\xBC")
    # Generated from packet 89/90
    controlWrite(0x40, 0xA0, 0x0023, 0x0000, b"\x02\x01\xBC")
    # Generated from packet 91/92
    controlWrite(0x40, 0xA0, 0x002B, 0x0000, b"\x02\x01\xBC")
    # Generated from packet 93/94
    controlWrite(0x40, 0xA0, 0x0033, 0x0000, b"\x02\x01\xBC")
    # Generated from packet 95/96
    controlWrite(0x40, 0xA0, 0x003B, 0x0000, b"\x02\x01\xBC")
    # Generated from packet 97/98
    controlWrite(0x40, 0xA0, 0x0043, 0x0000, b"\x02\x01\x00")
    # Generated from packet 99/100
    controlWrite(0x40, 0xA0, 0x004B, 0x0000, b"\x02\x01\xBC")
    # Generated from packet 101/102
    controlWrite(0x40, 0xA0, 0x0053, 0x0000, b"\x02\x01\x80")
    # Generated from packet 103/104
    controlWrite(0x40, 0xA0, 0x005B, 0x0000, b"\x02\x01\xBC")
    # Generated from packet 105/106
    controlWrite(0x40, 0xA0, 0x0063, 0x0000, b"\x02\x01\xBC")
    # Generated from packet 107/108
    controlWrite(0x40, 0xA0, 0x0100, 0x0000, b"\x02\x06\x1F\x00\x02\x01\xBC\x00\x02\x01\xBC\x00\x02\x01\xBC\x00")
    # Generated from packet 109/110
    controlWrite(0x40, 0xA0, 0x0110, 0x0000, b"\x02\x01\xBC\x00\x02\x01\xBC\x00\x02\x01\xBC\x00\x02\x01\xBC\x00")
    # Generated from packet 111/112
    controlWrite(0x40, 0xA0, 0x0120, 0x0000, b"\x02\x01\xBC\x00\x02\x01\xBC\x00\x02\x01\xBC\x00\x02\x01\xBC\x00")
    # Generated from packet 113/114
    controlWrite(0x40, 0xA0, 0x0130, 0x0000, b"\x02\x01\xBC\x00\x02\x01\xBC\x00\x02\x01\xBC\x00\x02\x01\xBC\x00")
    # Generated from packet 115/116
    controlWrite(0x40, 0xA0, 0x0140, 0x0000, b"\x02\x01\xBC\x00\x02\x01\xBC\x00\x02\x01\xBC\x00\x02\x01\xBC\x00")
    # Generated from packet 117/118
    controlWrite(0x40, 0xA0, 0x0150, 0x0000, b"\x02\x01\xBC\x00\x02\x01\xBC")
    # Generated from packet 119/120
    controlWrite(0x40, 0xA0, 0x0180, 0x0000, b"\x02\x01\xBC\x00\x02\x01\xBC\x00\x02\x01\xBC\x00\x02\x01\xBC\x00")
    # Generated from packet 121/122
    controlWrite(0x40, 0xA0, 0x0190, 0x0000, b"\x02\x01\xBC\x00\x02\x01\xBC\x00\x02\x01\xBC\x00\x02\x01\xBC\x00")
    # Generated from packet 123/124
    controlWrite(0x40, 0xA0, 0x01A0, 0x0000, b"\x02\x01\xBC\x00\x02\x01\xBC\x00\x02\x01\xBC\x00\x02\x01\xBC\x00")
    # Generated from packet 125/126
    controlWrite(0x40, 0xA0, 0x01B0, 0x0000, b"\x02\x01\xBC\x00\x02\x01\xBC\x00\x02\x01\xBC\x00\x32")
    # Generated from packet 127/128
    controlWrite(0x40, 0xA0, 0x0200, 0x0000, b"\x55\x53\x42\x20\x46\x69\x6C\x74\x65\x72\x20\x57\x68\x65\x65\x6C")
    # Generated from packet 129/130
    controlWrite(0x40, 0xA0, 0x0210, 0x0000, b"\x00\x46\x69\x6E\x67\x65\x72\x20\x4C\x61\x6B\x65\x73\x20\x49\x6E")
    # Generated from packet 131/132
    controlWrite(0x40, 0xA0, 0x0220, 0x0000, b"\x73\x74\x72\x75\x6D\x65\x6E\x74\x61\x74\x69\x6F\x6E\x2C\x20\x4C")
    # Generated from packet 133/134
    controlWrite(0x40, 0xA0, 0x0230, 0x0000, b"\x2E\x4C\x2E\x43\x2E\x00\x31\x2E\x30\x00\x75\x81\x7F\x90\x7F\xD6")
    # Generated from packet 135/136
    controlWrite(0x40, 0xA0, 0x0240, 0x0000, b"\x74\x0A\xF0\x90\x78\x4A\xE0\x54\xF0\x44\x00\xF0\x90\x78\x49\x74")
    # Generated from packet 137/138
    controlWrite(0x40, 0xA0, 0x0250, 0x0000, b"\x01\xF0\x90\x7F\x93\x74\x00\xF0\x90\x7F\x9C\x74\xF1\xF0\x74\x00")
    # Generated from packet 139/140
    controlWrite(0x40, 0xA0, 0x0260, 0x0000, b"\xF5\x80\x90\x7F\x94\x74\x00\xF0\x90\x7F\x9D\x74\x7F\xF0\x74\x00")
    # Generated from packet 141/142
    controlWrite(0x40, 0xA0, 0x0270, 0x0000, b"\xF5\x90\x90\x7F\x95\x74\x00\xF0\x90\x7F\x9E\x74\xFF\xF0\x74\x00")
    # Generated from packet 143/144
    controlWrite(0x40, 0xA0, 0x0280, 0x0000, b"\xF5\xA0\x90\x78\x43\x74\xFE\xF0\x90\x78\x47\x74\xFF\xF0\xD2\xB1")
    # Generated from packet 145/146
    controlWrite(0x40, 0xA0, 0x0290, 0x0000, b"\x78\x01\x90\x7E\x00\x74\x00\xF0\x74\xA0\x91\xC4\x78\x10\x90\x7E")
    # Generated from packet 147/148
    controlWrite(0x40, 0xA0, 0x02A0, 0x0000, b"\x00\x74\xA1\x91\xFF\xC2\xB1\x90\x7E\x09\xE0\xF5\x38\xA3\xE0\xF5")
    # Generated from packet 149/150
    controlWrite(0x40, 0xA0, 0x02B0, 0x0000, b"\x39\xA3\xE0\xF5\x3A\xA3\xE0\xF5\x3B\xA3\xE0\xF5\x3C\xA3\xE0\xF5")
    # Generated from packet 151/152
    controlWrite(0x40, 0xA0, 0x02C0, 0x0000, b"\x3D\xC2\x01\xC2\x02\xE5\x80\x03\x54\x07\x64\x07\x60\x06\xD2\x02")
    # Generated from packet 153/154
    controlWrite(0x40, 0xA0, 0x02D0, 0x0000, b"\x74\x07\x80\x04\xD2\x01\x74\x06\x90\x07\x42\xF0\x90\x7F\xAC\x74")
    # Generated from packet 155/156
    controlWrite(0x40, 0xA0, 0x02E0, 0x0000, b"\x00\xF0\x90\x7F\xAD\x74\x00\xF0\x90\x7F\xAE\x74\x01\xF0\x90\x7F")
    # Generated from packet 157/158
    controlWrite(0x40, 0xA0, 0x02F0, 0x0000, b"\xAF\x74\x01\xF0\x90\x7F\xA9\x74\xFF\xF0\xA3\xF0\x75\x89\x01\xE5")
    # Generated from packet 159/160
    controlWrite(0x40, 0xA0, 0x0300, 0x0000, b"\x8E\x44\x18\xF5\x8E\xD2\x8C\x90\x7F\xDE\x74\x57\xF0\x90\x7F\xDD")
    # Generated from packet 161/162
    controlWrite(0x40, 0xA0, 0x0310, 0x0000, b"\x74\x01\xF0\xD2\xE8\xD2\xAF\x74\xC8\xB1\x6D\x90\x7F\xD6\x74\x06")
    # Generated from packet 163/164
    controlWrite(0x40, 0xA0, 0x0320, 0x0000, b"\xF0\x74\xC8\xB1\x6D\x75\x32\x0A\x75\x31\x0A\x75\x34\x00\x75\x35")
    # Generated from packet 165/166
    controlWrite(0x40, 0xA0, 0x0330, 0x0000, b"\x00\x75\x36\x00\x75\x37\x00\xC2\x03\x75\x3E\x00\x75\x3F\x00\x75")
    # Generated from packet 167/168
    controlWrite(0x40, 0xA0, 0x0340, 0x0000, b"\x40\x00\x75\x41\x00\xD2\xA9\xC2\xB1\x90\x7F\xC9\xF0\x90\x7F\xC8")
    # Generated from packet 169/170
    controlWrite(0x40, 0xA0, 0x0350, 0x0000, b"\xE0\x20\xE1\xF9\xC2\xA9\xD2\xB1\x91\xAB\x90\x7D\xC0\xE0\xC4\x54")
    # Generated from packet 171/172
    controlWrite(0x40, 0xA0, 0x0360, 0x0000, b"\x0F\x90\x03\x67")
    # Generated from packet 173/174
    controlWrite(0x40, 0xA0, 0x0364, 0x0000, b"\x23\x23\x73\x02\x03\xA7\x00\x02\x03\xA7\x00\x02\x03\xA7\x00\x02")
    # Generated from packet 175/176
    controlWrite(0x40, 0xA0, 0x0374, 0x0000, b"\x03\xA7\x00\x02\x03\xA7\x00\x02\x03\xA7\x00\x02\x04\x1C\x00\x02")
    # Generated from packet 177/178
    controlWrite(0x40, 0xA0, 0x0384, 0x0000, b"\x04\x29\x00\x02\x03\xAB\x00\x02\x03\xF8\x00\x02\x04\x0A\x00\x02")
    # Generated from packet 179/180
    controlWrite(0x40, 0xA0, 0x0394, 0x0000, b"\x03\xA7\x00\x02\x03\xA7\x00\x02\x03\xA7\x00\x02\x03\xA7\x00\x02")
    # Generated from packet 181/182
    controlWrite(0x40, 0xA0, 0x03A4, 0x0000, b"\x04\x48\x00\x74\x02\x81\xA3\x90\x7D\xC1\xE0\x54\x07\x90\x03\xB7")
    # Generated from packet 183/184
    controlWrite(0x40, 0xA0, 0x03B4, 0x0000, b"\x23\x23\x73\x02\x03\xA7\x00\x02\x03\xD7\x00\x02\x03\xEB\x00\x02")
    # Generated from packet 185/186
    controlWrite(0x40, 0xA0, 0x03C4, 0x0000, b"\x03\xA7\x00\x02\x03\xA7\x00\x02\x03\xA7\x00\x02\x03\xE1\x00\x02")
    # Generated from packet 187/188
    controlWrite(0x40, 0xA0, 0x03D4, 0x0000, b"\x04\x29\x00\x90\x7E\x01\x74\x11\xF0\x74\x02\x81\xA3\x90\x7E\x01")
    # Generated from packet 189/190
    controlWrite(0x40, 0xA0, 0x03E4, 0x0000, b"\x74\x03\xF0\x74\x02\x81\xA3\x90\x7E\x01\xE5\x80\x03\x54\x07\xF0")
    # Generated from packet 191/192
    controlWrite(0x40, 0xA0, 0x03F4, 0x0000, b"\x74\x02\x81\xA3\x90\x7D\xC0\xE0\x54\x0F\xF5\x36\xA3\xE0\xF5\x37")
    # Generated from packet 193/194
    controlWrite(0x40, 0xA0, 0x0404, 0x0000, b"\xC2\x00\x74\x02\x81\xA3\x90\x7D\xC0\xE0\x54\x0F\xF5\x36\xA3\xE0")
    # Generated from packet 195/196
    controlWrite(0x40, 0xA0, 0x0414, 0x0000, b"\xF5\x37\xD2\x00\x74\x02\x81\xA3\x90\x7E\x01\xE0\x24\x3E\xF8\xE6")
    # Generated from packet 197/198
    controlWrite(0x40, 0xA0, 0x0424, 0x0000, b"\xF0\x74\x02\x80\x7A\x90\x7E\x00\xE0\x54\xF0\x45\x36\xF0\xA3\xE5")
    # Generated from packet 199/200
    controlWrite(0x40, 0xA0, 0x0434, 0x0000, b"\x36\x45\x37\x60\x04\xE5\x37\x80\x06\xE5\x35\x60\x02\x74\x01\xF0")
    # Generated from packet 201/202
    controlWrite(0x40, 0xA0, 0x0444, 0x0000, b"\x74\x02\x80\x5B\xD2\xA9\x20\xB0\x0B\xC2\x00\x75\x37\x64\xE5\x37")
    # Generated from packet 203/204
    controlWrite(0x40, 0xA0, 0x0454, 0x0000, b"\x60\xFC\x80\xF0\xD2\x03\xD2\x00\x75\x36\x0F\xE5\x36\x45\x37\x60")
    # Generated from packet 205/206
    controlWrite(0x40, 0xA0, 0x0464, 0x0000, b"\x1B\x20\xB0\xF7\xC2\xA9\x75\x36\x00\x75\x37\x00\x75\x3E\x00\x75")
    # Generated from packet 207/208
    controlWrite(0x40, 0xA0, 0x0474, 0x0000, b"\x3F\x00\x75\x40\x00\x75\x41\x00\xC2\x03\x80\x06\x90\x7E\x00\x74")
    # Generated from packet 209/210
    controlWrite(0x40, 0xA0, 0x0484, 0x0000, b"\x01\xF0\x74\x02\x80\x19\x78\x01\x90\x7E\x00\x74\x00\xF0\x74\xA0")
    # Generated from packet 211/212
    controlWrite(0x40, 0xA0, 0x0494, 0x0000, b"\x91\xC4\x78\x10\x90\x7E\x00\x74\xA1\x91\xFF\x74\x10\x80\x00\x60")
    # Generated from packet 213/214
    controlWrite(0x40, 0xA0, 0x04A4, 0x0000, b"\x04\x90\x7F\xB9\xF0\x61\x45\x90\x7D\xC0\x05\x86\x90\x7E\x00\x05")
    # Generated from packet 215/216
    controlWrite(0x40, 0xA0, 0x04B4, 0x0000, b"\x86\x75\x30\x40\xE0\xA3\x05\x86")
    # Generated from packet 217/218
    controlWrite(0x40, 0xA0, 0x04BC, 0x0000, b"\xF0\xA3\x05\x86\xD5\x30\xF5\x22\x75\x86\x01\xF9\x90\x7F\xA5\xE0")
    # Generated from packet 219/220
    controlWrite(0x40, 0xA0, 0x04CC, 0x0000, b"\x44\x80\xF0\xA3\xE9\xC2\xE0\xF0\x90\x7F\xA5\xE0\x30\xE0\xFC\x30")
    # Generated from packet 221/222
    controlWrite(0x40, 0xA0, 0x04DC, 0x0000, b"\xE1\x12\x20\xE2\x0F\xE8\x60\x0C\x75\x86\x00\xE0\xA3\x05\x86\xA3")
    # Generated from packet 223/224
    controlWrite(0x40, 0xA0, 0x04EC, 0x0000, b"\xF0\x18\x80\xE4\x90\x7F\xA5\xE0\x44\x40\xF0\xE0\x20\xE6\xFC\x75")
    # Generated from packet 225/226
    controlWrite(0x40, 0xA0, 0x04FC, 0x0000, b"\x86\x00\x22\x75\x86\x01\xF9\x90\x7F\xA5\xE0\xD2\xE7\xF0\xA3\xE9")
    # Generated from packet 227/228
    controlWrite(0x40, 0xA0, 0x050C, 0x0000, b"\xD2\xE0\xF0\x90\x7F\xA5\xE0\x30\xE0\xFC\x30\xE1\x28\x20\xE2\x25")
    # Generated from packet 229/230
    controlWrite(0x40, 0xA0, 0x051C, 0x0000, b"\xB8\x01\x04\xE0\xD2\xE5\xF0\xA3\xE0\x90\x7F\xA5\xE0\x30\xE0\xFC")
    # Generated from packet 231/232
    controlWrite(0x40, 0xA0, 0x052C, 0x0000, b"\x20\xE2\x12\xB8\x02\x03\xD2\xE5\xF0\xA3\xE0\x05\x86\xF0\xA3\x05")
    # Generated from packet 233/234
    controlWrite(0x40, 0xA0, 0x053C, 0x0000, b"\x86\x18\xE8\x70\xE4\x90\x7F\xA5\xE0\xD2\xE6\xF0\xE0\x20\xE6\xFC")
    # Generated from packet 235/236
    controlWrite(0x40, 0xA0, 0x054C, 0x0000, b"\x75\x86\x00\x22\x00\x00\x22\x00\x00\x00\x00\x22\xB1\x53\xB1\x53")
    # Generated from packet 237/238
    controlWrite(0x40, 0xA0, 0x055C, 0x0000, b"\xB1\x53\xB1\x53\xB1\x53\xB1\x53\xB1\x53\xB1\x53\xB1\x53\xB1\x53")
    # Generated from packet 239/240
    controlWrite(0x40, 0xA0, 0x056C, 0x0000, b"\x22\xF5\x30\xB1\x75\xD5\x30\xFB\x22\x90\xFB\x50\xA3\xE5\x82\x45")
    # Generated from packet 241/242
    controlWrite(0x40, 0xA0, 0x057C, 0x0000, b"\x83\x70\xF9\x22\x05\x06\x0A\x09\xC0\xD0\xC0\xE0\xC0\x82\xC0\x83")
    # Generated from packet 243/244
    controlWrite(0x40, 0xA0, 0x058C, 0x0000, b"\x75\x8C\xD1\x75\x8A\x37\xD5\x31\x1E\xE5\x32\xF5\x31\xE5\x36\x45")
    # Generated from packet 245/246
    controlWrite(0x40, 0xA0, 0x059C, 0x0000, b"\x37\x45\x35\x60\x75\xE5\x35\x70\x06\x75\x34\x05\x75\x35\x0A\xE5")
    # Generated from packet 247/248
    controlWrite(0x40, 0xA0, 0x05AC, 0x0000, b"\x34\x60\x06\xC2\x80\x15\x34\x80\x61\x30\x03\x05\x20\xB0\x11\x80")
    # Generated from packet 249/250
    controlWrite(0x40, 0xA0, 0x05BC, 0x0000, b"\x59\x30\x01\x0C\x30\x00\x09\x20\xB0\x06\x75\x36\x00\x75\x37\x00")
    # Generated from packet 251/252
    controlWrite(0x40, 0xA0, 0x05CC, 0x0000, b"\xE5\x36\x45\x37\x60\x3A\x15\x37\xE5\x37\xF4\x70\x02\x15\x36")
    # Generated from packet 253/254
    controlWrite(0x40, 0xA0, 0x05DB, 0x0000, b"\x20\x00\x0C\x05\x33\x05\x3E\xE5\x3E\x70\x0F\x05\x3F\x80\x0B\x15")
    # Generated from packet 255/256
    controlWrite(0x40, 0xA0, 0x05EB, 0x0000, b"\x33\x15\x3E\xE5\x3E\xF4\x70\x02\x15\x3F\xE5\x33\x54\x03\x90\x05")
    # Generated from packet 257/258
    controlWrite(0x40, 0xA0, 0x05FB, 0x0000, b"\x80\x93\x54\x0F\xC4\xF5\x30\xE5\x80\x54\x0F\x45\x30\xF5\x80\x80")
    # Generated from packet 259/260
    controlWrite(0x40, 0xA0, 0x060B, 0x0000, b"\x0A\x15\x35\xE5\x35\x70\x04\xD2\x80\x80\x00\xD0\x83\xD0\x82\xD0")
    # Generated from packet 261/262
    controlWrite(0x40, 0xA0, 0x061B, 0x0000, b"\xE0\xD0\xD0\x32\xC0\xD0\xC0\xE0\xC0\x82\xC0\x83\x90\x7F\xE9\xE0")
    # Generated from packet 263/264
    controlWrite(0x40, 0xA0, 0x062B, 0x0000, b"\x54\x0F\x23\x23\x90\x06\x33\x73\x02\x06\x7F\x00\x02\x07\x1C\x00")
    # Generated from packet 265/266
    controlWrite(0x40, 0xA0, 0x063B, 0x0000, b"\x02\x07\x1C\x00\x02\x07\x1C\x00\x02\x07\x1C\x00\x02\x07\x1C\x00")
    # Generated from packet 267/268
    controlWrite(0x40, 0xA0, 0x064B, 0x0000, b"\x02\x06\xAC\x00\x02\x07\x1C\x00\x02\x07\x1C\x00\x02\x06\x73\x00")
    # Generated from packet 269/270
    controlWrite(0x40, 0xA0, 0x065B, 0x0000, b"\x02\x07\x1C\x00\x02\x07\x1C\x00\x02\x07\x1C\x00\x02\x07\x1C\x00")
    # Generated from packet 271/272
    controlWrite(0x40, 0xA0, 0x066B, 0x0000, b"\x02\x07\x1C\x00\x02\x07\x1C\x00\x02\x07\x13\x90\x7F\x00\x74\x01")
    # Generated from packet 273/274
    controlWrite(0x40, 0xA0, 0x067B, 0x0000, b"\xF0\x02\x07\x13\x90\x7F\xE8\xB4\x80\x0B\x90\x7F\x00\x74\x00\xF0")
    # Generated from packet 275/276
    controlWrite(0x40, 0xA0, 0x068B, 0x0000, b"\xA3\xF0\x02\x07\x13\xB4\x81\x0B\x90\x7F\x00\x74\x00\xF0\xA3\xF0")
    # Generated from packet 277/278
    controlWrite(0x40, 0xA0, 0x069B, 0x0000, b"\x02\x07\x13\xB4\x82\x7B\x90\x7F\x00\x74\x00\xF0\xA3\xF0\x02\x07")
    # Generated from packet 279/280
    controlWrite(0x40, 0xA0, 0x06AB, 0x0000, b"\x13\x90\x7F\xE8\xE0\xB4\x80\x69\x90\x7F\xEB\xE0\x54\x03\x23\x23")
    # Generated from packet 281/282
    controlWrite(0x40, 0xA0, 0x06BB, 0x0000, b"\x90\x06\xBF\x73\x02\x07\x1C\x00\x02\x06\xCF\x00\x02\x06\xD4\x00")
    # Generated from packet 283/284
    controlWrite(0x40, 0xA0, 0x06CB, 0x0000, b"\x02\x06\xD9\x00\x90\x07\x38\x80\x30\x90\x07\x4A\x80\x2B\x90\x7F")
    # Generated from packet 285/286
    controlWrite(0x40, 0xA0, 0x06DB, 0x0000, b"\xEA\xE0\x70\x05\x90\x07\x7F\x80\x20\xD5\xE0\x05\x90\x07\x83\x80")
    # Generated from packet 287/288
    controlWrite(0x40, 0xA0, 0x06EB, 0x0000, b"\x18\xD5\xE0\x2D\x20\x01\x08\x20\x02\x0A\x90\x07\xCD\x80\x0A\x90")
    # Generated from packet 289/290
    controlWrite(0x40, 0xA0, 0x06FB, 0x0000, b"\x07\xFB\x80\x05\x90\x08\x1B\x80\x00\xE5\x83\x85\x82\x1E\x90\x7F")
    # Generated from packet 291/292
    controlWrite(0x40, 0xA0, 0x070B, 0x0000, b"\xD4\xF0\xE5\x1E\xA3\xF0\x80\x00\x90\x7F\xB4\xE0\x44\x02\xF0\x80")
    # Generated from packet 293/294
    controlWrite(0x40, 0xA0, 0x071B, 0x0000, b"\x07\x90\x7F\xB4\xE0\x44\x03\xF0\xE5\x91\xC2\xE4\xF5\x91\x90\x7F")
    # Generated from packet 295/296
    controlWrite(0x40, 0xA0, 0x072B, 0x0000, b"\xAB\x74\x01\xF0\xD0\x83\xD0\x82\xD0\xE0")
    # Generated from packet 297/298
    controlWrite(0x40, 0xA0, 0x0735, 0x0000, b"\xD0\xD0\x32\x12\x01\x10\x01\xFF\xFF\xFF\x40\x18\x0F\x06\x00\x00")
    # Generated from packet 299/300
    controlWrite(0x40, 0xA0, 0x0745, 0x0000, b"\x01\x01\x02\x00\x01\x09\x02\x35\x00\x01\x01\x00\x80\x32\x09\x04")
    # Generated from packet 301/302
    controlWrite(0x40, 0xA0, 0x0755, 0x0000, b"\x00\x00\x05\xFF\x00\x00\x00\x07\x05\x81\x03\x10\x00\x00\x07\x05")
    # Generated from packet 303/304
    controlWrite(0x40, 0xA0, 0x0765, 0x0000, b"\x82\x02\x40\x00\x00\x07\x05\x02\x02\x40\x00\x00\x07\x05\x84\x02")
    # Generated from packet 305/306
    controlWrite(0x40, 0xA0, 0x0775, 0x0000, b"\x40\x00\x00\x07\x05\x04\x02\x40\x00\x00\x04\x03\x09\x04\x4A\x03")
    # Generated from packet 307/308
    controlWrite(0x40, 0xA0, 0x0785, 0x0000, b"\x46\x00\x69\x00\x6E\x00\x67\x00\x65\x00\x72\x00\x20\x00\x4C\x00")
    # Generated from packet 309/310
    controlWrite(0x40, 0xA0, 0x0795, 0x0000, b"\x61\x00\x6B\x00\x65\x00\x73\x00\x20\x00\x49\x00\x6E\x00\x73\x00")
    # Generated from packet 311/312
    controlWrite(0x40, 0xA0, 0x07A5, 0x0000, b"\x74\x00\x72\x00\x75\x00\x6D\x00\x65\x00\x6E\x00\x74\x00\x61\x00")
    # Generated from packet 313/314
    controlWrite(0x40, 0xA0, 0x07B5, 0x0000, b"\x74\x00\x69\x00\x6F\x00\x6E\x00\x2C\x00\x20\x00\x4C\x00\x2E\x00")
    # Generated from packet 315/316
    controlWrite(0x40, 0xA0, 0x07C5, 0x0000, b"\x4C\x00\x2E\x00\x43\x00\x2E\x00\x2E\x03\x46\x00\x4C\x00\x49\x00")
    # Generated from packet 317/318
    controlWrite(0x40, 0xA0, 0x07D5, 0x0000, b"\x20\x00\x55\x00\x53\x00\x42\x00\x20\x00\x53\x00\x74\x00\x65\x00")
    # Generated from packet 319/320
    controlWrite(0x40, 0xA0, 0x07E5, 0x0000, b"\x70\x00\x70\x00\x65\x00\x72\x00\x20\x00\x44\x00\x65\x00\x76\x00")
    # Generated from packet 321/322
    controlWrite(0x40, 0xA0, 0x07F5, 0x0000, b"\x69\x00\x63\x00\x65\x00\x20\x03\x46\x00\x4C\x00\x49\x00\x20\x00")
    # Generated from packet 323/324
    controlWrite(0x40, 0xA0, 0x0805, 0x0000, b"\x55\x00\x53\x00\x42\x00\x20\x00\x46\x00\x6F\x00\x63\x00\x75\x00")
    # Generated from packet 325/326
    controlWrite(0x40, 0xA0, 0x0815, 0x0000, b"\x73\x00\x65\x00\x72\x00\x2A\x03\x46\x00\x4C\x00\x49\x00\x20\x00")
    # Generated from packet 327/328
    controlWrite(0x40, 0xA0, 0x0825, 0x0000, b"\x55\x00\x53\x00\x42\x00\x20\x00\x46\x00\x69\x00\x6C\x00\x74\x00")
    # Generated from packet 329/330
    controlWrite(0x40, 0xA0, 0x0835, 0x0000, b"\x65\x00\x72\x00\x20\x00\x57\x00\x68\x00\x65\x00\x65\x00\x6C\x00")
    # Generated from packet 331/338
    controlWrite(0x40, 0xA0, 0x7F92, 0x0000, b"\x00")
    # PcapGen: generated 391 packets
    # PcapGen device filter: dropped 92 / 391 packets
    # VidpidFilter: dropped 0 / 154 entries, want None
    # SetupFilter: dropped 19 / 155 entries

def open_dev(vid_want, pid_want, usbcontext=None):
    if usbcontext is None:
        usbcontext = usb1.USBContext()
    
    print("Scanning for devices...")
    for udev in usbcontext.getDeviceList(skip_on_error=True):
        vid = udev.getVendorID()
        pid = udev.getProductID()
        if (vid, pid) == (vid_want, pid_want):
            print("Found device")
            print("Bus %03i Device %03i: ID %04x:%04x" % (
                udev.getBusNumber(),
                udev.getDeviceAddress(),
                vid,
                pid))
            return udev.open()
    raise Exception("Failed to find a device")

def main():
    import argparse 

    vid_want = 0x0F18
    pid_want = 0x0005
    parser = argparse.ArgumentParser(description="Replay captured USB packets")
    args = parser.parse_args()

    usbcontext = usb1.USBContext()
    dev = open_dev(vid_want, pid_want, usbcontext)
    dev.claimInterface(0)
    dev.resetDevice()
    replay(dev)

if __name__ == "__main__":
    main()

